### ISSUE TITLE
The DebugCamera should be independently controllable

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#116]
G3D apps like to have a separate `DebugCamera` that you can switch to for debugging purposes. We should change the way FPSci handles the player camera to decouple the `DebugCamera` from the player's view and camera.

**Comment by bboudaoud-nv** [comment]
This was related to an issue with the `PhysicsScene` interacting with the `GApp` implementation of the `SceneEditorWindow` within the `DeveloperWindow`. The "fix" for now is to remove/re-create the `SceneEditorWindow` within our app using a `shared_ptr<PhysicsScene>` instead of a `shared_ptr<Scene>`.

**Comment by bboudaoud-nv** [comment]
This was related to an issue with the `PhysicsScene` interacting with the `GApp` implementation of the `SceneEditorWindow` within the `DeveloperWindow`. The "fix" for now is to remove/re-create the `SceneEditorWindow` within our app using a `shared_ptr<PhysicsScene>` instead of a `shared_ptr<Scene>`.
