### ISSUE TITLE
Fake HUD Features

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#117]
In order to make screenshots look more like real games, it would be helpful to support the following kinds of 2D-layer HUD items.

* Minimap
* Weapon Icon(s)
* Team member/enemy icons (showing team alive-dead status)
* Ability status (icons showing if abilities have charges yet, and cooldown status)

Since these are currently planned to be cosmetic only, I propose they be bundled together and called "fakeHUD" or something similar to make it clear that these aren't hooked up and functional features.

If we figure out real versions of these for specific mechanics at some point in the future, then we can add additional features at that point.

**Comment by bboudaoud-nv** [comment]
Some of these are cosmetic and others seem to be easy enough to implement as "real" features (i.e. no need to fake it).

 **"Fake" Only Features**
The following features are things that would likely be faked since FPSci doesn't have any direct use of/for them right now and they require some more major work:

* Mini-map: Not sure how this would work for arbitrary maps
* Team member icons: No notion of "team members" in FPSci currently
* Ability status: No  notion of "abilities" in FPSci currently.

**Possible Real Features**
* Weapon icon: Unless this needs to be dynamic it could easily be added in the weapon specification.
* Enemy icons: Easy to show these (we already show combat text/health bars). Just need to decide on a dynamic (i.e. is there a "ping" style system?)

Implementation Approach
---
I'd suggest we consider having an optional "Static HUD Array" in the experiment config which contains additional 2D content to be "applied as static HUD" to the player's view. This would looks something like a list of structures containing an image filename, along with scaling and placement information.

Using this "Static HUD Array" experiment developers could add arbitrary (static) 2D content to the HUD. All 2D HUD content would be rendered in `onGraphics2D()` (i.e. would not be "delayed" with the render latency). This is not an issue so long as only static content is provided.
