### ISSUE TITLE
Mouse Sensitivity Issue from PlayerEntity->onSimulation()

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#120]
The use of angular velocity in `PlayerEntity->onSImulation()` effectively doubled mouse sensitivity when `scene()->onSimulation()` was called twice (see issue #113). Since we've corrected the double-call, we also need to get rid of the `/2.0` in the mouse sensitivity.

Thanks to @pknowlesnv for pointing this out.

**Comment by bboudaoud-nv** [comment]
Looking deeper here, this might be a good chance to fix many "fudge factors" around mouse sensitivity (not just the `/2.0` mentioned above).

In `App::updateMouseSensitivity()` we have (historically) multiplied by `1920` (assumed to have something to do with screen resolution, but not well understood) then applied an additional (multiplicative) fudge factor of `1.0675`. Combining these effects, we multiply by ~`2050` in this method.

In `PlayerEntity::updateFromInput()` we divide the mouse sensitivity by `2000`.

The combined gain is `1.025`, just 2.5% from doing none of this math to begin with. My intuition is to remove all of these constants and re-measure the accuracy of the cm/360 sensitivity setting. If we pass a simple test with these parameters set carefully I suggest we drop them entirely.

Eventually we may want to consider moving to "direct" mouse control (i.e. operate on the mouse's integrated position rather than the change frame-to-frame).

**Comment by jspjutNV** [comment]
I agree we should rework the mouse gain, and we need to fix the calibration factors.

I haven't been able to figure out how the values we get from mouse motion map to the physical mouse movement. If we could get a "cm" or "inches" number, then it would be much easier to convert to degrees since we want to specify in cm/360 degrees. 

I had assumed that the dx and dy inputs for the mouse were measured in "dots" which would map to inches by way of the DPI setting in the mouse, which is why I backed out some of the seemingly random factors in the current code. The weirdest factor to me was the 1920 one, so I sort of assumed there needed to be some factor of the screen resolution in there, but that didn't make much sense to me. When I did the calibration before, I also ended up with a final factor of 1.0675 that again based only on measurements and no first principles understanding.

@bboudaoud-nv , since you mentioned it, how do you get the mouse's integrated position when we're in the FPS movement mode? This mode (in Windows I believe, and likely other operating systems) reports the mouse delta only, then resets the mouse to the center of the screen to allow for continuous motion. In other words the integrated mouse position is always `center + (dx, dy)` We could accumulate those values ourselves, but isn't it more "direct" to use the actual values as they're being reported at the lowest level available to us to control the change in view?

**Comment by bboudaoud-nv** [comment]
This is a bit confusing, but I will take an attempt at answering what _should_ happen, we will need to guarantee this is what _is_ happening independently. I'll break the process into 2 steps (since this is how it's done in code): getting to a radians/dot sensitivity and applying an update based on a reported delta XY value from the mouse.

**Getting to Radians/Dot**
The user provides their DPI (dots/in) and mouse sensitivity (cm/360), the `PlayerEntity::mouseSensitivity` is set with units of `dots/rad` (by way of `App::updateMouseSensitivity()`) as follows:

```
cm/dot = (2.54 cm/in) / DPI setting (dots/in)
rad/cm =  2π / sensitivity (cm/turn = cm/360)

rad/dot = rad/cm * cm/dot = (2π * 2.54)/(sensitivity * DPI)
```

**Applying the Update to a Mouse ΔX/Y Input**
Inside of the `PlayerEntity::updateFromInput()` we then multiply the ΔX/Y of the mouse by this `rads/dot` value to turn `Δdots` into `Δrads` for player view rotation and add it to the existing viewer heading yaw/pitch in the `PlayerEntity::onSimulation()` as follows:

In `PlayerEntity::updateFromInput()`:
```
Δyaw (Δradians) = Mouse ΔX (Δdots) * mouseSensitivity (rad/dot)
Δpitch (Δradians) = Mouse ΔY (Δdots) * mouseSensitivity (rad/dot)
```
In `PlayerEntity::onSimulation()`
```
heading (radians) += Δyaw (Δradians)
tilt (radians) += Δpitch (Δradians)
```

I've left out most details regarding range clamping/player turn scale above to keep things simple, but the actual source isn't much more complicated than that.
