### ISSUE TITLE
Named Spawn Locations in Scene Files

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#133]
@pknowlesnv suggested that we supported named spawn locations in our `scene.any` file specification. This would allow the experiment/session level configuration to specify different spawn points within a scene. This would be supported as either:

1. Part of our `PhysicsScene` class
2. Part of a child class to `PhysicsScene` that specifies more FPSci-specific behavior

Player "respawn" behavior can be set to either use a fixed spawn point or revert to the closest spawn point to where the player ended the last session/fell below the respawn height.

If no spawn point is specified in the experiment config then the first "named" location is used as the spawn location. These spawn locations could/should include both the player position (XYZ) as well as view direction (heading).

**Comment by bboudaoud-nv** [comment]
@morgan3d suggested we use `MarkerEntity`s to setup the spawn points in the scene in a G3D compliant way. This makes sense and is something we should look into as a solution that avoids duplicating effort.

We would need to add a `String` (or possibly `Array<String>` if we want "randomized" spawn behavior) field to the `FpsConfig` to allow the experiment designer to specify a named marker entity from the scene file at which to spawn the player.

**Comment by jspjutNV** [comment]
I like both of those recommendations. I think the `MarkerEntity` one is high priority and we should get done as soon as reasonable since it affects workflow for designing new scenes and experiments generally.

The second one for randomizing spawn behavior by listing the spawn locations in the `FpsConfig` could probably wait until someone has a need for it. It may also run into issues where a set of targets needs to be matched with the spawn location, though I suppose that can be partially solved by using separate sessions for coupled spawns and targets.

**Comment by bboudaoud-nv** [comment]
This could be implemented as a part of the longer term restructure suggested in #174.

**Comment by jspjutNV** [comment]
@bboudaoud-nv I believe #176 addressed this issue and we can close it. I'm closing this, but if it turns out that we needed something else for this, we can re-open.

For what it's worth, I believe this is solved by specifying different cameras in the scene and then specifying which camera to use in the scene structure per experiment/session as wanted.
