### ISSUE TITLE
block-based design of session

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#142]
- Add “block” concept to each session
  - Blocks are a way to represent “training” and “real” sessions we’ve had in the past
- Repeat targets/trial counts for each “block”
  - All blocks have the same trial count and targets
- Print a message to the screen for each “block”
  - Message configurable in experimentConfig.
    - Default: “You have finished Block [index] / [total block count].”
  - Mostly an indication that the subject can take a break.
- Still session complete message when session is complete.
  - Block complete message won’t get printed at all in a single block session.
- Still 1 output file per session
  - Trials table will now include a Block index
- Progress tracking is done on Session level (not on Block level)
  - Example: Assume a subject stopped the experiment after Block 3 in Session 2. When restarting FPSci, I want it to start from Block 1 in Session 2.

**Comment by bboudaoud-nv** [comment]
Is there _any_ behavior we want to specify differently between blocks (other than the printed message)? For example in the past I remember things like printing score vs not based on "real" vs "training" sessions.

If we do want this ability block implementation might be a bit more difficult/complicated as it will need to include a way for users to specify this behavior on a block-wise basis. If not the implementation should be relatively straightforward.

**Comment by joohwankimNV** [comment]
Nope. I don't have any behavioral variations that I can think of now.

**Comment by jspjutNV** [comment]
The "real" vs "training" was sort of a quick way to get 2 copies of the same session to be able to execute. The order was only enforced by the `userstatus.Any` file, so you could mess that up with the wrong setting. I believe you could just name the sessions `"Block 1/4"`, `"Block 2/4"`, `"Block 3/4"`, `"Block 4/4"` to get the same behavior with the current code. 

If we think it makes sense to add a fuller-featured support for this methodology (it sounds like a good idea), then I could see it working by specifying a `numBlocks` or `count` or similar in each session in the `experimentconfig.Any`, and then having the `userstatus.Any` track the `lastCompletedBlock` along side each of the sessions in the `completedSessions` array. This would mean the entries in `completedSessions` would become Tables instead of the current individual strings.

**Comment by joohwankimNV** [comment]
Reading Josef's comment, adding one more behavior for blocks.

I want blocks to provide an explicit opportunity to take short breaks, but session be one run. So if a subject stops after Block #3 in Session #2 and closes FPSci, I want FPSci to start from the beginning of Session #2 (Block #1 in Session #2). In other words, FPSci tracks the progress on Session level but not Block level. Again, it seems like no additional implementation is needed in terms of tracking progress.

I will modify the first post accordingly.

**Comment by jspjutNV** [comment]
> I want blocks to provide an explicit opportunity to take short breaks, but session be one run. So if a subject stops after Block 3 in Session 2 and closes FPSci, I want FPSci to start from the beginning of Session 2 (Block 1 in Session 2). In other words, FPSci tracks the progress on Session level but not Block level. Again, it seems like no additional implementation is needed in terms of tracking progress.

Okay,  that makes it easier to support. So the application is required to keep running between blocks of the same session. We should be sure to document this behavior clearly.

**Comment by bboudaoud-nv** [comment]
The affiliated [branch/PR](https://github.com/NVlabs/abstract-fps/pull/149) now contains the `blockCount` based integer specification.
