### ISSUE TITLE
FPSci crashes if no `startupconfig.Any` is present

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#277]
You can reproduce this by downloading [v21.02.01](https://github.com/NVlabs/abstract-fps/releases/tag/v21.02.01) and double clicking `FirstPersonScience.exe`. On first run, it will create the `startupconfig.Any` and crash. The second run after the file is created works as expected.

**Comment by bboudaoud-nv** [comment]
This was introduced by #262, in that the default `StartupConfig` constructor does not populate the `experimentList` with `defaultExperiment` if no experiments are present unless loading from Any.

Rather than simply adding this manually, I'm debating adding a `StartupConfig::load()` static method that will handle this and always use the Any constructor rather than needing to keep 2 different constructors in sync.
