### ISSUE TITLE
Target Size should mean something

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#45]
In the config files when we set a target's `visualSize` value, the size controls the scaling relative to other size values, but it doesn't have a meaning in world space or visual angle or anything related.

We should adjust the scaling factors to make the target size set the world space size of the target. I recommend that the size variable should set the horizontal width of the target in meters. So a value of `0.10` would mean 10 centimeters.

This will interact with the `distance` setting and probably will mean breaking compatibility with older experiment configs since realistic target sizes will make the most sense further away from the viewer than we've been placing them so far.

**Comment by bboudaoud-nv** [comment]
I think moving away from specifying the target size in visual angle is a good idea if we are planning for more complex target motions (per Issue #44) since we can't necessarily guarantee this is respected.

I think specifying the absolute size of the target (in world space) is a fine approach, though we could also continue to specify a  scale factor rather than an absolute size (though this makes the experiment designer's life more difficult). Unless someone else feels strongly I think I prefer world-space size per @jspjutNV's suggestion.

I'll look into getting the size of the bounding box so we can still do scale factors correctly.

**Comment by joohwankimNV** [comment]
I agree with the 'physical size in the world' approach.

**Comment by bboudaoud-nv** [comment]
A first-pass implementation of this real-world size-based scaling has been implemented. This should be more rigorously tested before closing the issue.

**Comment by bboudaoud-nv** [comment]
With the [latest commit](https://github.com/NVlabs/abstract-fps/commit/2a24f16cb1223e999de2f9053851e5a0a26caa7e) we can verify that the target size is scaled as expected (using `debugDraw()` of spheres). There is possible future work in "correctly" aligning the bounding box for sizing, but for now I'll close this issue.
