### ISSUE TITLE
Storing gamer/camera pose

### ISSUE THREAD

**Issue by kamranbinaeeNV** [NVlabs/abstract-fps#49]
Since the gamer is allowed to move we have to store the 3D pose in the player action table. I have implemented a version and it's working since I don't have access I can do pull request if it's fine with everyone. Btw, I suggest keeping the current azimuth and elevation and just add position + orientation columns. This will allow a post-hoc analysis & sanity check for 3D calculations.

**Comment by bboudaoud-nv** [comment]
This makes a lot of sense (adding X,Y,Z to the `Player_Action` table in the results). This way we get the player location for any given action ('hit', 'miss', etc). If you'd like to issue a pull request for this I'd be happy to merge it in. Otherwise we can get you access for push then do a quick code review prior to integrating the source.

**Comment by kamranbinaeeNV** [comment]
Sure, let me try the pull request first.

**Comment by bboudaoud-nv** [comment]
Support for this has been added as of a [recent commit](https://github.com/NVlabs/abstract-fps/commit/91431cf93f12410a2228a70e02e0965a90f7c208). I believe player X,Y,Z coordinates were all that was requested. Check it out and see if this meets your needs (if so we can close this item).

**Comment by bboudaoud-nv** [comment]
On second thought I'll close this now. Reopen/let me know if the need is not met.
