### ISSUE TITLE
Make sure default config values are sensible

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#66]
The default configuration for experiments, sessions, trials and weapons should all be sensible. This issue is for tracking a pass through these defaults to make sure they all make sense.

**Comment by bboudaoud-nv** [comment]
Default user name (for `UserConfig`) is `anon` with 800DPI and 12.75 cm/360°. Is this what we want? Also (this might be another issue) but I'm fairly sure we can remove the `currentSession` member since this is now handled with user status.

**Comment by bboudaoud-nv** [comment]
Default weapon configuration uses a 2 round/s, 1 hit destroy (1 damage per hit) solution w/o a rendered model. Is this the desired behavior? If so should we remove the `modelSpec` from the default?

More generally the behavior of this weapon is setup to mimic the 1-hit weapon from our early SIGA experiments (`renderDecals=true`, `renderBullets=false`, `renderMuzzleFlash=false`), is this what we want to stick with?

**Comment by bboudaoud-nv** [comment]
Default `TargetConfig` uses a `destSpace=world` but does not include a valid `AABox` for the `bounds` parameter (`bbox` member field). We should either figure out a way to initialize this `AABox` or move (back) to a `player` space default target.

Non-`player` space targets cannot "just work" by definition since the coordinate frame for the scene could change arbitrarily. This is another reason to consider moving towards a `player` space default target.

**Comment by bboudaoud-nv** [comment]
The default value for `count` in the `TrialCount` class is `0` but I'm not sure what behavior this creates. If we'd like we could support "never ending" trials using a value of `0` or `-1` for `count`. Otherwise I'm assuming that this `0` value _should_ mean that no trials are performed. This isn't necessarily a problem since the default session-level behavior is to create no sessions currently. Is this desired?

**Comment by bboudaoud-nv** [comment]
This post details issues in the common/general parameters setup using `FpsConfig`.

- The default `sceneName` could be moved to an empty string that indicates keeping a previously loaded scene/reverting to an application default (something that comes w/ the app)
- The default `frameRate` is set to 0, which I believe unlocks the frame rate, still we should be explicit here...
- The default `jumpVelocity` seems a bit high for the default `playerGravity` value
- `showHUD` is disabled by default (kills all HUD elements) should we enable this instead?
- Additional HUD elements (`showBanner`, `showPlayerHealthBar`, `showAmmo`) are set to `false`, should these be enabled if we set `showHUD=true` (see item above)
- The `renderClickPhoton` is set to `true` by default, but most users won't have access to click-to-photon monitoring hardware, should we disable this by default
- Target health bars and floating combat text are disabled by default (`showTargetHealthBars` and `showCombatText` are `false`) do we want to enable either of these (especially if we move away from a 1-hit weapon)?
- Are the `dummy` target parameters (`dummyTargetSize`, `dummyTargetColor`) correct for what we want?

**Comment by bboudaoud-nv** [comment]
The default `sessDescription` is `"training"`, but perhaps we want something a bit more generic? Default `SessionConfig` does not include any trials (and moreover the default `ExperimentConfig` doesn't include any default `SessionConfig`s).

**Comment by bboudaoud-nv** [comment]
In `ExperimentConfig` the `expDescription` field is uninitialized, harmonize with `sessDescription` and likely provide some default value (even if just an empty string).

In addition the deafult `sessions` and `targets` arrays are empty, meaning no (playable) sessions are created if no (custom) config files are present on disk.

**Comment by bboudaoud-nv** [comment]
We've addressed many of the comments above, changes made include:

* Removing the `currentSession` field from the `UserConfig`
* Setting `renderClickPhoton=false` by default
* Harmonizing the session/experiment `description` defaults
* Adding a descriptive exception structure around empty `users` arrays in the `UserTable`
* Setting the default `trialCount = 1` for `TrialCount` objects (also see `defaultTrialCount`)
* Setting more appropriate defaults for `jumpVelocity` and `playerGravity`
* Updating the `dummy` target to use new language (`reference` target)
* New mechanic for dealing with (now default) empty `sceneName` field

Since no targets/sessions are added by default (we will keep this behavior for now) the `TargetConfig` issues are not a big problem. New/invalid user issues have been largely mitigated (now throw descriptive exceptions or auto-populate the user). The team has agreed on most of the default values set as part of this effort. Additional issues can be opened in the future (referencing this issue) to address remaining items.
