### ISSUE TITLE
Reticle/Crosshair Customization

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#77]
Users have expressed an interest in customizing their crosshair in the application. (For now) we want to add *per-user* customized reticles/crosshairs with user options for size and color configuration. The current spec suggests using a field for selecting the crosshair/reticle type, as well as sizing and a field for a (4-channel) color spec.

We might also choose to add a "fire animation" to the cross hair (scale based on time since a fire event). In this case we can make the size field an array of min/max sizes for the reticle/crosshair. This feature is not required, but may be implemented along with the other settings.

In the future we may also add crosshair/reticle control as part of the `FpsConfig` this will need to have a priority (relative to the user-specified value) and is considered auxiliary to this issue.

**Comment by jspjutNV** [comment]
The "fire animation" of the cross hair would probably want to be designed to mimic a game that implements that kind of animation (such as CS:GO or Fortnite). That animation does a couple things, including telling the user that the recent shots have reduced the weapon accuracy, in which case it should be coupled to a weapon recoil configuration parameter.

Since the urgent issue is user customize-able reticle shapes and colors, we should refer to this issue for discussion on animation and additional configuration spots when we prioritize those issues.

**Comment by bboudaoud-nv** [comment]
Recent commits add support for customization of crosshairs/reticles. The available parameters are documented in the [`userConfigReadme.md` file](https://github.com/NVlabs/abstract-fps/blob/master/docs/userConfigReadme.md). I'm assuming this takes care of the ask for now, and will close this issue.

If I've left off any implementation we would like to have completed let me know and we can re-open this issue/start a new one.
