### ISSUE TITLE
App launch failure if the default user completed all sessions.

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#81]
App stops with an error if the default user completed all the sessions.

**Comment by bboudaoud-nv** [comment]
This seems to be related to issues in the `getTargetsForSession()` call and its call  in turn to `getSessionIndex()` which throws and exception when it cannot find a valid session id.

We attempt to work around this using the `m_hasSession` flag (indicating whether there is a valid session to load); however, this isn't working because we've created a default session config already (and potentially invoked the wrong constructor for `Session`) at line 923 of `App.cpp`.

We can either:

1. Fix the broken `m_hasSession` flag to get things working
2. Leave the default session and come up w/ the correct behavior for this session

**Comment by bboudaoud-nv** [comment]
I believe this issue is now resolved, I'm going to close this. We can re-open if needed.
