### ISSUE TITLE
Injecting latency on 2D interface

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#83]
After a major re-work a couple weeks ago, the 2D interface is not affected by latency injection any more. Fix is needed for latency injection mechanism to include 2D renderings.

**Comment by bboudaoud-nv** [comment]
This was caused by moving the HUD elements from `onPostProcessHDR3DEffects()` into `onGraphics2D()`. Since the frame queuing is all handled within `onGraphics3D()` which (internally) calls `onPostProcessHDR3DEffects()` moving this to the `onGraphics2D()` resulted in the HUD being non-latency matched to the 3D content.

The quick fix is to move to move all of the HUD calls we don't want to be instantaneous back into `onPostProcessHDR3DEffects()` and out of `onGraphics2D()`. Alternatively/in the future we could always use a separate queue in `onGraphics2D()` to keep things lined up/allow creation of time offsets between 3D game state and HUD state.

**Comment by bboudaoud-nv** [comment]
I've moved most HUD elements/2D effects (i.e. target health bars/combat text) back into `onPostProcessHDR3DEffects()` which brings most things back to being delayed by `frameDelay`. We can always improve upon this structure in the future, but for now I believe it addresses the issue.

**Comment by joohwankimNV** [comment]
Confirmed it works! Thank you!
