### ISSUE TITLE
Inconsistent `PlayerEntity::moveRate` update mechanism

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#87]
`PlayerEntity::moveRate` is being updated on a frame-by-frame basis when `playMode = false` but not so when `playMode = true`. We need to make the update mechanism consistent so that experimenter can change `moveRate` in a consistent way for both play modes.

**Comment by bboudaoud-nv** [comment]
Adding some info to @joohwankimNV's point above. 

The reason this happens is a result of how the dynamic settings for player parameters are implemented in the application. Currently (when `playMode=false`) the user is free to open up the "Player Controls" window either using the file-style top menu, or by pressing `2` during play. From this window the user can modify the player settings normally set by the experiment/session config (i.e. `playerHeight`, `moveRate`, etc) dynamically in the application.

Since (one) goal of the `playMode=false` setup is to allow users to edit/export config parameters it made sense to have the selections made in the menu items bound to the (current) session's config values. However, the `PlayerEntity` (currently) has it's own copies of these fields used for actual camera motion, and these need to be set from the session config variables bound to the GUI elements. We do this in `App::onSimulation()`  by adding a copy from `sessConfig` --> `player` fields conditional on the `startupConfig.playMode` being `false`.

I see 2 possible ways to resolve this issue and move forward:
1. We alter `PlayerEntity` to store its member fields by reference, this way a single data bind to the GUI elements/update when the session changes should allow us to remove any need for a copy-over of player parameters
2. We change the data binding such that the GUI controls directly set the parameters for the `PlayerEntity`. We can remove the need for a copy-over in `onSimulation()` since the player parameters are updated directly by the GUI elements. However, we would now need to add a copy from `PlayerEntity` --> `SessionConfig` if we wanted to export the player settings to a file.

There are probably more options here, but I may take a look at implementing (1) before (2).

**Comment by joohwankimNV** [comment]
I see. Option (1) sounds good to me, too. Thanks for taking care of it!

**Comment by jspjutNV** [comment]
I agree with having only 1 copy of a piece of data whenever it makes sense. The only reason I can think of to not directly modify the value loaded from the config is if the value is written out to the config automatically, making dynamic testing permanent since that could ruin experiment configuration.

Do we save the config automatically, or does the user get a chance to choose whether to save these player configuration parameters after they've been changed?

Also, going a bit deeper, I'm not sure I see the reason why the player movement needs to be changeable in `playMode=true` since in my mind that indicates we're in "run an experiment" mode and parameters like player motion seem like they should be hard coded at that point. Maybe there's some use of changing player motion speed that I'm missing here.

**Comment by joohwankimNV** [comment]
On the need of hard-coding player position: I agree that it's not needed in most cases, and I myself did not think it would be needed ever. But it became necessary for an internal experiment, and I thought it could be useful to keep this option generally open.

**Comment by bboudaoud-nv** [comment]
I believe this particular difference should now be resolved. There is no longer a `PlayerEntity::moveRate` field to update. Instead a pointer is bound to the `App::sessConfig->moveRate`. Now the player controls/updates to the session config during the trial will update the player directly. We can likely close this issue.
