### ISSUE TITLE
Additional parameter request for any config

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#88]
Below are a set of desired parameters useful for an upcoming experiments.
`disablePlayerMoveBetweenTrials`, if set to true, makes player move rate be 0 between trials.
`resetPlayerPositionPerTrial`, if set to true, resets player position at the time of trial completion.
`playerDefaultPosition`, if given, overwrites the default position set by `scene.Any` file (PlayerEntity / frame).
The variable names are a bit long... feel free to shorten it if better option occurs!

**Comment by jspjutNV** [comment]
The first 2 seem like reasonable proposals.

The 3rd on `playerDefaultPosition`, is it not enough to just change the `PlayerEntity::CFrame` in the `.Scene.Any` file? Is this something you want to be able to set per session or trial?

**Comment by bboudaoud-nv** [comment]
I believe @jspjutNV has the right approach here. We shouldn't duplicate player positioning between the scene and experiment config files if we can avoid it. Previously we've kept the player with the scene, since this spawn position is scene dependent.

One quick question for the first 2 parameters (`disablePlayerMotionBetweenTrials` and `resetPlayerPositionPerTrial`) do we have a suggestion for defaults? Right now I'll go w/ our historical values of `false` for both, but I can set them however we'd like.

**Comment by bboudaoud-nv** [comment]
@joohwankimNV I believe this issue is now closed. If the solution provided doesn't meet your needs feel free to let me know and I can re-open this to address any remaining issues.
