### ISSUE TITLE
Rapid fire weapon sound

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#99]
Rapid fire weapons would benefit from some sort of continuous fire sound depending on the fire rate. I believe the best way to achieve this is to add a flag to the weapon config to indicate that the audio associated with a "rapid fire" or "continuous fire" weapon should be played on a loop while the mouse button is down, and should stop when the mouse up event happens.

This is split out from #96 .

**Comment by bboudaoud-nv** [comment]
The current approach supports rapid fire weapons, but just by playing a sound repeatedly as each shot is fired. Is the request to move over to an alternate sound that plays unmatched to the exact weapon fire rate? I agree we still need to implement something for a continuous fire weapon.

Is there a performance/quality issue we are worried about with the current approach? If not I'd be likely to keep the current implementation for single shot/automatic weapons and implement a new case for "laser" style "continuous fire" weapons.

**Comment by jspjutNV** [comment]
The issue I'm worried about with the current approach is that it would cause the single sound to overlap many times, which is undesireable in the sound. I'd expect the implementation to regular weapons to `sound.play()` every time the weapon fires.

Then for "continuous fire" weapons, the `sound.play()` should be called on mouse down and `sound.stop()` should happen on mouse up.

**Comment by bboudaoud-nv** [comment]
We should consider this more carefully.  Currently I don't _hear_ issues, but problems could only occur at higher fire rates than what I've tested. 

Ideally we would check the duration of the sound against the `firePeriod` of the weapon and do something conditionally here. If the sound duration is less than the `firePeriod` I see no reason to call `sound.stop()` since this might "cut off" the firing sound mid-shot. If the duration is greater than `firePeriod` then we have the case where multiple sounds will be overlapped/might produce undesirable artifacts. I can look into what happens when this is the case.

We will certainly need some logic like this for laser weapons (i.e. an infinitely looping sound that can be stopped when the mouse goes up).

**Comment by bboudaoud-nv** [comment]
Looped audio is [now supported for lasers](https://github.com/NVlabs/abstract-fps/commit/1a10e05d699ef823e4eb0a35ada19daa78f60304) this could easily be extended to automatic firing weapons as well. The only problem with this is that the weapon developer will now need to trim their audio appropriately for the looping. 

We should discuss what is the right approach to move forward with for `autoFire = true` weapons which are not "lasers" (i.e. have `firePeriod` > 0).

**Comment by bboudaoud-nv** [comment]
Assuming this is fine, closing the issue.
